<?php

namespace ContainerSuIT5rS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CE70c2yService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cE70c2y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cE70c2y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repository' => ['privates', 'App\\Repository\\RealPropertyRepository', 'getRealPropertyRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\RealPropertyRepository',
        ]);
    }
}
