<?php

namespace ContainerJawL2ik;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRealPropertyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.AeosDtN.App\Entity\RealProperty' shared service.
     *
     * @return \App\Entity\RealProperty
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.AeosDtN": it references class "App\\Entity\\RealProperty" but no such service exists.');
    }
}
