<?php

namespace ContainerJawL2ik;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStripeClientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Stripe\StripeClient' shared autowired service.
     *
     * @return \Stripe\StripeClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/stripe/stripe-php/lib/BaseStripeClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/stripe/stripe-php/lib/StripeClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/stripe/stripe-php/lib/StripeStreamingClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/stripe/stripe-php/lib/BaseStripeClient.php';
        include_once \dirname(__DIR__, 4).'/vendor/stripe/stripe-php/lib/StripeClient.php';

        return $container->privates['Stripe\\StripeClient'] = new \Stripe\StripeClient($container->getEnv('STRIPE_API_KEY'));
    }
}
