<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSuIT5rS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSuIT5rS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSuIT5rS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSuIT5rS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSuIT5rS\App_KernelDevDebugContainer([
    'container.build_hash' => 'SuIT5rS',
    'container.build_id' => '16ecec00',
    'container.build_time' => 1675172319,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSuIT5rS');
